name: Web CI

on:
  push:
    branches: [ main, "feature/**", "codex/**" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: web-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm ci

      # npm10-safe TS check, запускаем внутри web/ и по web/tsconfig.build.json
      - name: Type check (build only)
        run: npx --yes -p typescript@5.6.3 tsc -p tsconfig.build.json --noEmit

      - name: Format check
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --ci

      - name: Build
        run: npm run build
