# .github/workflows/web-ci.yml
name: Web CI

on:
  push:
    branches: [ main, "feature/**", "codex/**" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install
        working-directory: web
        run: npm ci

      - name: Format check
        working-directory: web
        run: npm run format:check

      - name: Lint
        working-directory: web
        run: npm run lint

      - name: Test
        working-directory: web
        run: npm test -- --ci

      - name: Build
        working-directory: web
        run: npm run build

      # (опционально) строгая проверка типов на всём репо,
      # даже если typescript не в web/package.json:
      - name: Type check (root strict)
      - run: npx --yes -p typescript@5.6.3 tsc -p tsconfig.json --noEmit
